version: '2'
services:
  webserver:
    image: adrazich/fit-php7-oci8-laravel
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
